version: '3.8'
services:
  web:
    build:
      context: .
    command: gunicorn --bind 0.0.0.0:8000 oauth_project.wsgi --workers=4
    expose:
      - "8000"
    ports:
      - "9000:8000"
    depends_on:
      - db
    links:
      - db:db
  db:
    image: postgres:13
    build: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: systemmanagerdb
    ports:
      - '5432:5432'

