# Generated by Django 4.1 on 2022-10-30 01:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacidad', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proyecto', models.TextField(blank=True)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_inicio', models.DateField(null=True)),
                ('fecha_fin', models.DateField(null=True)),
                ('creado_by', models.IntegerField()),
                ('tipos_storys', models.JSONField(null=True)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oauth_project.estado')),
                ('scrum_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True)),
                ('equipo', models.JSONField()),
                ('nro_sprint', models.IntegerField()),
                ('objetivo', models.TextField()),
                ('fecha_inicio', models.DateField(null=True)),
                ('cant_dias_duracion', models.IntegerField()),
                ('fecha_fin', models.DateField(null=True)),
                ('carga_horas_sprint_total', models.IntegerField(null=True)),
                ('carga_horas_diarias_equipo', models.IntegerField(null=True)),
                ('tipos_storys', models.JSONField()),
                ('json_informe_historico_finalizacion', models.JSONField(null=True)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oauth_project.estado')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oauth_project.proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='TipoUserStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('en_uso', models.BooleanField(default=False)),
                ('estados', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='UserStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('detalles', models.TextField()),
                ('user_point', models.SmallIntegerField()),
                ('business_value', models.SmallIntegerField()),
                ('estado', models.TextField()),
                ('estimacion_horas', models.IntegerField()),
                ('estimacion_horas_inicial', models.IntegerField()),
                ('eventos', models.JSONField()),
                ('cancelado', models.BooleanField(default=False)),
                ('finalizado', models.BooleanField(default=False)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oauth_project.proyecto')),
                ('sprint_asoc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='oauth_project.sprint')),
                ('tipo_user_story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oauth_project.tipouserstory')),
                ('usuario_asignado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RolProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oauth_project.proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PermisoRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permiso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oauth_project.permiso')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oauth_project.rolproyecto')),
            ],
        ),
        migrations.CreateModel(
            name='Miembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oauth_project.rolproyecto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Integrante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant_horas_dias', models.IntegerField(default=0)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oauth_project.equipo')),
                ('integrante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='equipo',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oauth_project.proyecto'),
        ),
    ]
