# Generated by Django 4.1 on 2023-10-08 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolesSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
    ]
