# Generated by Django 4.1 on 2023-10-12 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_project', '0004_remove_rolusuario_descripcion_rolusuario_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('precio_minorista', models.IntegerField()),
                ('precio_intermedio', models.IntegerField()),
                ('precio_mayorista', models.IntegerField()),
                ('cantidad_stock_inicial', models.IntegerField()),
            ],
        ),
    ]
