# Generated by Django 4.1 on 2023-10-12 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_project', '0007_rename_cantidad_stock_inicial_producto_cantidad_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('telefono', models.TextField()),
                ('documento', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='producto',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
