# Generated by Django 4.1 on 2023-10-12 05:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_project', '0009_tipoventa_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha_pagado',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha_venta',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
