# Generated by Django 4.1 on 2023-10-12 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_project', '0010_alter_venta_fecha_pagado_alter_venta_fecha_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha_pagado',
            field=models.DateTimeField(),
        ),
    ]
