# Generated by Django 4.1 on 2023-10-12 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_project', '0011_alter_venta_fecha_pagado'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='cantidad_articulos',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venta',
            name='monto_total',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.IntegerField()),
                ('precio_total', models.IntegerField()),
                ('is_precio_especial', models.BooleanField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oauth_project.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oauth_project.venta')),
            ],
        ),
    ]
