# Generated by Django 4.1 on 2023-10-12 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_project', '0014_alter_venta_fecha_pagado_alter_venta_fecha_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='pagado',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
