# Generated by Django 4.1 on 2023-10-12 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_project', '0016_alter_venta_fecha_venta_alter_venta_pagado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='pagado',
            field=models.BooleanField(),
        ),
    ]
