# Generated by Django 4.1 on 2023-10-12 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_project', '0018_devoluciones'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Devoluciones',
            new_name='Devolucion',
        ),
    ]
