# Generated by Django 4.1 on 2023-10-12 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_project', '0019_rename_devoluciones_devolucion'),
    ]

    operations = [
        migrations.AddField(
            model_name='devolucion',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='oauth_project.cliente'),
            preserve_default=False,
        ),
    ]
