# Generated by Django 3.2.6 on 2023-10-28 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_project', '0022_tipopago'),
    ]

    operations = [
        migrations.AddField(
            model_name='devolucion',
            name='monto_devolucion',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
