# Generated by Django 3.2.6 on 2023-10-28 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_project', '0024_devolucion_venta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devolucion',
            name='monto_devolucion',
        ),
        migrations.AddField(
            model_name='devolucion',
            name='motivo_devolucion',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
