# Generated by Django 3.2.6 on 2023-10-29 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_project', '0026_devolucion_monto_devolucion'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrecioProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
