# Generated by Django 3.2.6 on 2023-10-29 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_project', '0028_auto_20231029_0430'),
    ]

    operations = [
        migrations.AddField(
            model_name='precioproducto',
            name='producto',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='oauth_project.producto'),
            preserve_default=False,
        ),
    ]
