# Generated by Django 3.2.6 on 2023-10-29 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_project', '0029_precioproducto_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precioproducto',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
