# Generated by Django 3.2.6 on 2023-10-29 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_project', '0030_alter_precioproducto_precio'),
    ]

    operations = [

    ]
