# Generated by Django 3.2.6 on 2023-10-30 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_project', '0031_producto_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoAutorizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
            ],
        )
    ]
