# Generated by Django 3.2.6 on 2023-10-30 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_project', '0032_auto_20231030_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='estado_autorizacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='oauth_project.estadoautorizacion'),
            preserve_default=False,
        )
    ]
