# Generated by Django 3.2.6 on 2023-10-30 02:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oauth_project', '0033_auto_20231030_0128'),
    ]

    operations = [

        migrations.CreateModel(
            name='AutorizacionesRealizadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.IntegerField()),
                ('precio_total', models.IntegerField()),
                ('is_precio_especial', models.BooleanField()),
                ('fecha_venta', models.DateTimeField()),
                ('estado_autorizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oauth_project.estadoautorizacion')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oauth_project.producto')),
                ('usuario_autorizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oauth_project.venta')),
            ],
        ),
    ]
