# Generated by Django 3.2.6 on 2023-10-30 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_project', '0034_auto_20231030_0230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autorizacionesrealizadas',
            old_name='fecha_venta',
            new_name='fecha_autorizacion',
        )
    ]
